{% set name = "taurus" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 80c6cf07a04d4e7af8508c1f1a106893bdce0313eb338a68ab0d0117eead5523

build:
  number: 0
  noarch: python

requirements:
  run:
    - {{ pin_subpackage('taurus-core', exact=True) }}
    - {{ pin_subpackage('taurus-qt', exact=True) }}

outputs:
  - name: taurus-core
    script: build_core.sh
    build:
      noarch: python
      entry_points:
        - taurus = taurus.cli:main
    requirements:
      host:
        - python >=3.6
        - pip
        - setuptools
      run:
        - python >=3.6
        - click
        - numpy >=1.1
        - packaging
        - pint >=0.8
        - setuptools
    test:
      imports:
        - taurus
        - taurus.core
        - taurus.external
        - taurus.cli
      commands:
        - pip check
        - taurus --help
      requires:
        - pip

  - name: taurus-qt
    build:
      noarch: python
    requirements:
      host:
        - python >=3.6
      run:
        - python >=3.6
        - {{ pin_subpackage('taurus-core', exact=True) }}
        - pyqt
        - pyqtwebengine
        - ply >=2.3
        - lxml >=2.1
        - guiqwt >=3
    test:
      imports:
        - taurus.qt
      commands:
        - taurus check-deps

about:
  home: http://www.taurus-scada.org
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  summary: A framework for scientific/industrial CLIs and GUIs
  description: |
    Taurus is a python framework for control and data
    acquisition CLIs and GUIs in scientific/industrial environments.
    It supports multiple control systems or data sources: Tango, EPICS,...
    New control system libraries can be integrated through plugins.
  doc_url: http://taurus-scada.org
  dev_url: https://gitlab.com/taurus-org/taurus

extra:
  recipe-maintainers:
    - ovallcorba
    - rhomspuron
    - beenje
    - cpascual
